-- N5 Vocabulary - Batch 6 (100 words)
-- Adjectives, adverbs, and essential expressions

DO $$
DECLARE
  inserted_count INTEGER;
BEGIN

INSERT INTO learning_items (
  type,
  jlpt_level,
  content,
  reading,
  meaning,
  category,
  subcategory,
  example_sentence,
  example_reading,
  example_translation,
  order_index,
  difficulty_level
)
VALUES
  -- い-Adjectives (601-640)
  ('vocabulary', 'N5', '多い', 'おおい', '많다', 'adjectives', 'i-adjective', '人が多いです。', 'ひとがおおいです。', '사람이 많아요.', 601, 1),
  ('vocabulary', 'N5', '少ない', 'すくない', '적다', 'adjectives', 'i-adjective', '人が少ないです。', 'ひとがすくないです。', '사람이 적어요.', 602, 1),
  ('vocabulary', 'N5', '長い', 'ながい', '길다', 'adjectives', 'i-adjective', '髪が長いです。', 'かみがながいです。', '머리가 길어요.', 603, 1),
  ('vocabulary', 'N5', '短い', 'みじかい', '짧다', 'adjectives', 'i-adjective', 'スカートが短いです。', 'すかーとがみじかいです。', '치마가 짧아요.', 604, 1),
  ('vocabulary', 'N5', '高い', 'たかい', '높다, 비싸다', 'adjectives', 'i-adjective', '山が高いです。', 'やまがたかいです。', '산이 높아요.', 605, 1),
  ('vocabulary', 'N5', '低い', 'ひくい', '낮다', 'adjectives', 'i-adjective', '椅子が低いです。', 'いすがひくいです。', '의자가 낮아요.', 606, 1),
  ('vocabulary', 'N5', '広い', 'ひろい', '넓다', 'adjectives', 'i-adjective', '部屋が広いです。', 'へやがひろいです。', '방이 넓어요.', 607, 1),
  ('vocabulary', 'N5', '狭い', 'せまい', '좁다', 'adjectives', 'i-adjective', '道が狭いです。', 'みちがせまいです。', '길이 좁아요.', 608, 1),
  ('vocabulary', 'N5', '厚い', 'あつい', '두껍다', 'adjectives', 'i-adjective', '本が厚いです。', 'ほんがあついです。', '책이 두꺼워요.', 609, 1),
  ('vocabulary', 'N5', '薄い', 'うすい', '얇다', 'adjectives', 'i-adjective', '紙が薄いです。', 'かみがうすいです。', '종이가 얇아요.', 610, 1),
  ('vocabulary', 'N5', '重い', 'おもい', '무겁다', 'adjectives', 'i-adjective', '荷物が重いです。', 'にもつがおもいです。', '짐이 무거워요.', 611, 1),
  ('vocabulary', 'N5', '軽い', 'かるい', '가볍다', 'adjectives', 'i-adjective', 'かばんが軽いです。', 'かばんがかるいです。', '가방이 가벼워요.', 612, 1),
  ('vocabulary', 'N5', '強い', 'つよい', '강하다', 'adjectives', 'i-adjective', '風が強いです。', 'かぜがつよいです。', '바람이 강해요.', 613, 1),
  ('vocabulary', 'N5', '弱い', 'よわい', '약하다', 'adjectives', 'i-adjective', '体が弱いです。', 'からだがよわいです。', '몸이 약해요.', 614, 1),
  ('vocabulary', 'N5', '速い', 'はやい', '빠르다', 'adjectives', 'i-adjective', '車が速いです。', 'くるまがはやいです。', '차가 빨라요.', 615, 1),
  ('vocabulary', 'N5', '遅い', 'おそい', '느리다, 늦다', 'adjectives', 'i-adjective', '電車が遅いです。', 'でんしゃがおそいです。', '전철이 느려요.', 616, 1),
  ('vocabulary', 'N5', '早い', 'はやい', '이르다', 'adjectives', 'i-adjective', '朝が早いです。', 'あさがはやいです。', '아침이 일러요.', 617, 1),
  ('vocabulary', 'N5', '近い', 'ちかい', '가깝다', 'adjectives', 'i-adjective', '駅が近いです。', 'えきがちかいです。', '역이 가까워요.', 618, 1),
  ('vocabulary', 'N5', '遠い', 'とおい', '멀다', 'adjectives', 'i-adjective', '学校が遠いです。', 'がっこうがとおいです。', '학교가 멀어요.', 619, 1),
  ('vocabulary', 'N5', '若い', 'わかい', '젊다', 'adjectives', 'i-adjective', '先生が若いです。', 'せんせいがわかいです。', '선생님이 젊어요.', 620, 1),
  ('vocabulary', 'N5', '古い', 'ふるい', '오래되다', 'adjectives', 'i-adjective', '家が古いです。', 'いえがふるいです。', '집이 오래됐어요.', 621, 1),
  ('vocabulary', 'N5', '新しい', 'あたらしい', '새롭다', 'adjectives', 'i-adjective', '靴が新しいです。', 'くつがあたらしいです。', '신발이 새로워요.', 622, 1),
  ('vocabulary', 'N5', '良い', 'よい/いい', '좋다', 'adjectives', 'i-adjective', '天気がいいです。', 'てんきがいいです。', '날씨가 좋아요.', 623, 1),
  ('vocabulary', 'N5', '悪い', 'わるい', '나쁘다', 'adjectives', 'i-adjective', '成績が悪いです。', 'せいせきがわるいです。', '성적이 나빠요.', 624, 1),
  ('vocabulary', 'N5', '正しい', 'ただしい', '옳다', 'adjectives', 'i-adjective', '答えが正しいです。', 'こたえがただしいです。', '답이 맞아요.', 625, 2),
  ('vocabulary', 'N5', '難しい', 'むずかしい', '어렵다', 'adjectives', 'i-adjective', '試験が難しいです。', 'しけんがむずかしいです。', '시험이 어려워요.', 626, 1),
  ('vocabulary', 'N5', '易しい', 'やさしい', '쉽다', 'adjectives', 'i-adjective', '問題が易しいです。', 'もんだいがやさしいです。', '문제가 쉬워요.', 627, 1),
  ('vocabulary', 'N5', '優しい', 'やさしい', '친절하다', 'adjectives', 'i-adjective', '先生が優しいです。', 'せんせいがやさしいです。', '선생님이 친절해요.', 628, 1),
  ('vocabulary', 'N5', '厳しい', 'きびしい', '엄격하다', 'adjectives', 'i-adjective', '父が厳しいです。', 'ちちがきびしいです。', '아버지가 엄격해요.', 629, 2),
  ('vocabulary', 'N5', '楽しい', 'たのしい', '즐겁다', 'adjectives', 'i-adjective', '旅行が楽しいです。', 'りょこうがたのしいです。', '여행이 즐거워요.', 630, 1),
  ('vocabulary', 'N5', '悲しい', 'かなしい', '슬프다', 'adjectives', 'i-adjective', '映画が悲しいです。', 'えいががかなしいです。', '영화가 슬퍼요.', 631, 1),
  ('vocabulary', 'N5', '嬉しい', 'うれしい', '기쁘다', 'adjectives', 'i-adjective', 'プレゼントが嬉しいです。', 'ぷれぜんとがうれしいです。', '선물이 기뻐요.', 632, 1),
  ('vocabulary', 'N5', '怖い', 'こわい', '무섭다', 'adjectives', 'i-adjective', 'お化けが怖いです。', 'おばけがこわいです。', '귀신이 무서워요.', 633, 1),
  ('vocabulary', 'N5', '痛い', 'いたい', '아프다', 'adjectives', 'i-adjective', '頭が痛いです。', 'あたまがいたいです。', '머리가 아파요.', 634, 1),
  ('vocabulary', 'N5', '眠い', 'ねむい', '졸리다', 'adjectives', 'i-adjective', 'とても眠いです。', 'とてもねむいです。', '너무 졸려요.', 635, 1),
  ('vocabulary', 'N5', '欲しい', 'ほしい', '갖고 싶다', 'adjectives', 'i-adjective', '車が欲しいです。', 'くるまがほしいです。', '차를 갖고 싶어요.', 636, 1),
  ('vocabulary', 'N5', '珍しい', 'めずらしい', '드물다', 'adjectives', 'i-adjective', '珍しい花です。', 'めずらしいはなです。', '드문 꽃이에요.', 637, 2),
  ('vocabulary', 'N5', 'すごい', 'すごい', '대단하다', 'adjectives', 'i-adjective', 'すごい景色です。', 'すごいけしきです。', '대단한 경치에요.', 638, 1),
  ('vocabulary', 'N5', 'おいしい', 'おいしい', '맛있다', 'adjectives', 'i-adjective', 'ケーキがおいしいです。', 'けーきがおいしいです。', '케이크가 맛있어요.', 639, 1),
  ('vocabulary', 'N5', 'まずい', 'まずい', '맛없다', 'adjectives', 'i-adjective', 'この料理はまずいです。', 'このりょうりはまずいです。', '이 요리는 맛없어요.', 640, 1),

  -- な-Adjectives (641-670)
  ('vocabulary', 'N5', '元気', 'げんき', '건강하다, 기운차다', 'adjectives', 'na-adjective', '元気です。', 'げんきです。', '건강해요.', 641, 1),
  ('vocabulary', 'N5', '綺麗', 'きれい', '예쁘다, 깨끗하다', 'adjectives', 'na-adjective', '花がきれいです。', 'はながきれいです。', '꽃이 예뻐요.', 642, 1),
  ('vocabulary', 'N5', '静か', 'しずか', '조용하다', 'adjectives', 'na-adjective', '図書館は静かです。', 'としょかんはしずかです。', '도서관은 조용해요.', 643, 1),
  ('vocabulary', 'N5', 'にぎやか', 'にぎやか', '시끌벅적하다', 'adjectives', 'na-adjective', '街がにぎやかです。', 'まちがにぎやかです。', '거리가 시끌벅적해요.', 644, 1),
  ('vocabulary', 'N5', '便利', 'べんり', '편리하다', 'adjectives', 'na-adjective', 'とても便利です。', 'とてもべんりです。', '매우 편리해요.', 645, 1),
  ('vocabulary', 'N5', '不便', 'ふべん', '불편하다', 'adjectives', 'na-adjective', '田舎は不便です。', 'いなかはふべんです。', '시골은 불편해요.', 646, 2),
  ('vocabulary', 'N5', '簡単', 'かんたん', '간단하다', 'adjectives', 'na-adjective', '問題が簡単です。', 'もんだいがかんたんです。', '문제가 간단해요.', 647, 1),
  ('vocabulary', 'N5', '複雑', 'ふくざつ', '복잡하다', 'adjectives', 'na-adjective', '道が複雑です。', 'みちがふくざつです。', '길이 복잡해요.', 648, 2),
  ('vocabulary', 'N5', '有名', 'ゆうめい', '유명하다', 'adjectives', 'na-adjective', '有名な歌手です。', 'ゆうめいなかしゅです。', '유명한 가수예요.', 649, 1),
  ('vocabulary', 'N5', '親切', 'しんせつ', '친절하다', 'adjectives', 'na-adjective', '先生は親切です。', 'せんせいはしんせつです。', '선생님은 친절해요.', 650, 1),
  ('vocabulary', 'N5', '丁寧', 'ていねい', '정중하다', 'adjectives', 'na-adjective', '丁寧な言葉です。', 'ていねいなことばです。', '정중한 말이에요.', 651, 2),
  ('vocabulary', 'N5', '真面目', 'まじめ', '성실하다', 'adjectives', 'na-adjective', '真面目な学生です。', 'まじめながくせいです。', '성실한 학생이에요.', 652, 2),
  ('vocabulary', 'N5', '賑やか', 'にぎやか', '활기차다', 'adjectives', 'na-adjective', '祭りが賑やかです。', 'まつりがにぎやかです。', '축제가 활기차요.', 653, 1),
  ('vocabulary', 'N5', '暇', 'ひま', '한가하다', 'adjectives', 'na-adjective', '今日は暇です。', 'きょうはひまです。', '오늘은 한가해요.', 654, 1),
  ('vocabulary', 'N5', '忙しい', 'いそがしい', '바쁘다', 'adjectives', 'i-adjective', '仕事が忙しいです。', 'しごとがいそがしいです。', '일이 바빠요.', 655, 1),
  ('vocabulary', 'N5', '大切', 'たいせつ', '소중하다', 'adjectives', 'na-adjective', '家族が大切です。', 'かぞくがたいせつです。', '가족이 소중해요.', 656, 1),
  ('vocabulary', 'N5', '大事', 'だいじ', '중요하다', 'adjectives', 'na-adjective', '健康が大事です。', 'けんこうがだいじです。', '건강이 중요해요.', 657, 1),
  ('vocabulary', 'N5', '必要', 'ひつよう', '필요하다', 'adjectives', 'na-adjective', 'お金が必要です。', 'おかねがひつようです。', '돈이 필요해요.', 658, 1),
  ('vocabulary', 'N5', '不要', 'ふよう', '불필요하다', 'adjectives', 'na-adjective', 'これは不要です。', 'これはふようです。', '이것은 불필요해요.', 659, 2),
  ('vocabulary', 'N5', '特別', 'とくべつ', '특별하다', 'adjectives', 'na-adjective', '特別な日です。', 'とくべつなひです。', '특별한 날이에요.', 660, 2),
  ('vocabulary', 'N5', '普通', 'ふつう', '보통', 'adjectives', 'na-adjective', '普通の人です。', 'ふつうのひとです。', '보통 사람이에요.', 661, 1),
  ('vocabulary', 'N5', '同じ', 'おなじ', '같다', 'adjectives', 'na-adjective', '同じ色です。', 'おなじいろです。', '같은 색이에요.', 662, 1),
  ('vocabulary', 'N5', '違う', 'ちがう', '다르다', 'verbs', 'basic', '答えが違います。', 'こたえがちがいます。', '답이 달라요.', 663, 1),
  ('vocabulary', 'N5', '似る', 'にる', '닮다', 'verbs', 'basic', '父に似ています。', 'ちちににています。', '아버지를 닮았어요.', 664, 1),
  ('vocabulary', 'N5', '似ている', 'にている', '비슷하다', 'adjectives', 'na-adjective', '色が似ています。', 'いろがにています。', '색이 비슷해요.', 665, 1),
  ('vocabulary', 'N5', '上手', 'じょうず', '잘하다', 'adjectives', 'na-adjective', 'ピアノが上手です。', 'ぴあのがじょうずです。', '피아노를 잘해요.', 666, 1),
  ('vocabulary', 'N5', '下手', 'へた', '못하다', 'adjectives', 'na-adjective', '料理が下手です。', 'りょうりがへたです。', '요리를 못해요.', 667, 1),
  ('vocabulary', 'N5', '得意', 'とくい', '자신있다', 'adjectives', 'na-adjective', '英語が得意です。', 'えいごがとくいです。', '영어에 자신있어요.', 668, 2),
  ('vocabulary', 'N5', '苦手', 'にがて', '서투르다', 'adjectives', 'na-adjective', '数学が苦手です。', 'すうがくがにがてです。', '수학을 서툴러해요.', 669, 1),
  ('vocabulary', 'N5', '好き', 'すき', '좋아하다', 'adjectives', 'na-adjective', '音楽が好きです。', 'おんがくがすきです。', '음악을 좋아해요.', 670, 1),

  -- Adverbs (671-700)
  ('vocabulary', 'N5', 'とても', 'とても', '매우', 'adverbs', 'degree', 'とても美しいです。', 'とてもうつくしいです。', '매우 아름다워요.', 671, 1),
  ('vocabulary', 'N5', 'すごく', 'すごく', '굉장히', 'adverbs', 'degree', 'すごく寒いです。', 'すごくさむいです。', '굉장히 추워요.', 672, 1),
  ('vocabulary', 'N5', 'たくさん', 'たくさん', '많이', 'adverbs', 'degree', '本をたくさん読みます。', 'ほんをたくさんよみます。', '책을 많이 읽어요.', 673, 1),
  ('vocabulary', 'N5', 'ちょっと', 'ちょっと', '조금', 'adverbs', 'degree', 'ちょっと待ってください。', 'ちょっとまってください。', '잠깐 기다려 주세요.', 674, 1),
  ('vocabulary', 'N5', '少し', 'すこし', '조금', 'adverbs', 'degree', '少し疲れました。', 'すこしつかれました。', '조금 피곤해요.', 675, 1),
  ('vocabulary', 'N5', 'もっと', 'もっと', '더', 'adverbs', 'degree', 'もっと勉強します。', 'もっとべんきょうします。', '더 공부해요.', 676, 1),
  ('vocabulary', 'N5', 'もう', 'もう', '이미, 벌써', 'adverbs', 'time', 'もう帰ります。', 'もうかえります。', '이제 가요.', 677, 1),
  ('vocabulary', 'N5', 'まだ', 'まだ', '아직', 'adverbs', 'time', 'まだ早いです。', 'まだはやいです。', '아직 일러요.', 678, 1),
  ('vocabulary', 'N5', 'もうすぐ', 'もうすぐ', '곧', 'adverbs', 'time', 'もうすぐ春です。', 'もうすぐはるです。', '곧 봄이에요.', 679, 1),
  ('vocabulary', 'N5', 'すぐ', 'すぐ', '곧, 바로', 'adverbs', 'time', 'すぐ行きます。', 'すぐいきます。', '바로 가요.', 680, 1),
  ('vocabulary', 'N5', 'ゆっくり', 'ゆっくり', '천천히', 'adverbs', 'manner', 'ゆっくり歩きます。', 'ゆっくりあるきます。', '천천히 걸어요.', 681, 1),
  ('vocabulary', 'N5', '早く', 'はやく', '빨리', 'adverbs', 'manner', '早く来てください。', 'はやくきてください。', '빨리 와 주세요.', 682, 1),
  ('vocabulary', 'N5', 'よく', 'よく', '잘, 자주', 'adverbs', 'manner', 'よく寝ます。', 'よくねます。', '잘 자요.', 683, 1),
  ('vocabulary', 'N5', 'たぶん', 'たぶん', '아마', 'adverbs', 'probability', 'たぶん雨です。', 'たぶんあめです。', '아마 비일 거예요.', 684, 1),
  ('vocabulary', 'N5', 'きっと', 'きっと', '꼭, 분명', 'adverbs', 'probability', 'きっと来ます。', 'きっときます。', '꼭 와요.', 685, 1),
  ('vocabulary', 'N5', 'ぜんぜん', 'ぜんぜん', '전혀', 'adverbs', 'degree', 'ぜんぜんわかりません。', 'ぜんぜんわかりません。', '전혀 모르겠어요.', 686, 1),
  ('vocabulary', 'N5', 'あまり', 'あまり', '별로, 그다지', 'adverbs', 'degree', 'あまり好きじゃないです。', 'あまりすきじゃないです。', '별로 안 좋아해요.', 687, 1),
  ('vocabulary', 'N5', 'いつも', 'いつも', '항상', 'adverbs', 'frequency', 'いつもここに来ます。', 'いつもここにきます。', '항상 여기 와요.', 688, 1),
  ('vocabulary', 'N5', 'よく', 'よく', '자주', 'adverbs', 'frequency', 'よく映画を見ます。', 'よくえいがをみます。', '자주 영화를 봐요.', 689, 1),
  ('vocabulary', 'N5', '時々', 'ときどき', '가끔', 'adverbs', 'frequency', '時々散歩します。', 'ときどきさんぽします。', '가끔 산책해요.', 690, 1),
  ('vocabulary', 'N5', 'たまに', 'たまに', '가끔', 'adverbs', 'frequency', 'たまに会います。', 'たまにあいます。', '가끔 만나요.', 691, 1),
  ('vocabulary', 'N5', '全部', 'ぜんぶ', '전부', 'adverbs', 'quantity', '全部食べました。', 'ぜんぶたべました。', '전부 먹었어요.', 692, 1),
  ('vocabulary', 'N5', 'みんな', 'みんな', '모두', 'adverbs', 'quantity', 'みんな来ました。', 'みんなきました。', '모두 왔어요.', 693, 1),
  ('vocabulary', 'N5', '一緒に', 'いっしょに', '함께', 'adverbs', 'manner', '一緒に行きましょう。', 'いっしょにいきましょう。', '함께 가요.', 694, 1),
  ('vocabulary', 'N5', '別々に', 'べつべつに', '따로따로', 'adverbs', 'manner', '別々に払います。', 'べつべつにはらいます。', '따로따로 내요.', 695, 2),
  ('vocabulary', 'N5', 'だんだん', 'だんだん', '점점', 'adverbs', 'change', 'だんだん暑くなります。', 'だんだんあつくなります。', '점점 더워져요.', 696, 1),
  ('vocabulary', 'N5', 'やっと', 'やっと', '겨우', 'adverbs', 'manner', 'やっと終わりました。', 'やっとおわりました。', '겨우 끝났어요.', 697, 2),
  ('vocabulary', 'N5', 'まっすぐ', 'まっすぐ', '똑바로', 'adverbs', 'direction', 'まっすぐ行きます。', 'まっすぐいきます。', '똑바로 가요.', 698, 1),
  ('vocabulary', 'N5', '特に', 'とくに', '특히', 'adverbs', 'emphasis', '特に好きです。', 'とくにすきです。', '특히 좋아해요.', 699, 2),
  ('vocabulary', 'N5', '本当に', 'ほんとうに', '정말로', 'adverbs', 'emphasis', '本当にありがとうございます。', 'ほんとうにありがとうございます。', '정말 감사합니다.', 700, 1);

SELECT COUNT(*) INTO inserted_count FROM learning_items WHERE order_index BETWEEN 601 AND 700;
RAISE NOTICE 'Batch 6 완료: % 단어 추가됨 (601-700)', inserted_count;

END $$;
